#!/usr/bin/env bash

if [ $(id -u) != '0' ]
then
	echo "You should execute me as root, or better, with sudo."
	exit 1
fi

clear
echo "Get more info at https://github.com/Natsec/flawless-hedgehog"

if [ $# -eq 1 ]
then
	config=$1
else
	config=/etc/apache2/apache2.conf && echo "[info] No parameter given, configuration file assumed to be $config"
fi

echo $config

backup=${config}.before_launching_flawless-hedgehog
cp $config $backup && echo "[info] Making a backup of your configuration file as  -->   ${backup}\n"
echo "\n# Security directives added by flawless-hedgehog.sh on $(date)" >> $config


#echo '          .:::::::::.   '
#echo '         :::::::::::::  '
#echo '        /. `::::::::::: '
#echo '       o__,_::::::::::° '


echo "\n\n Information leakage"
echo "##################################################"

# hide server signature
read -p "Disable server signature on error pages ? (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	echo 'ServerSignature Off' >> $config && echo "Disabling server signature on error pages: Directive 'ServerSignature' set to off."
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	read -p  "Disable server signature on error pages ? (y/n):" ans
fi


# hide version in HTTP header
read -p  "Hide Apache version in HTTP response header ? (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	echo 'ServerTokens Prod' >> $config && echo "Hidding Apache version in HTTP response header: Directive 'ServerTokens' set to Production mode."
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	read -p  "Hide Apache version in HTTP response header ? (y/n):" ans
fi


# disable etag header
read -p  "Disable Etag header ? (a remote attacker could obtain informations on your system) (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	echo 'FileETag None' >> $config && echo "Disabling Etag response header: Directive 'FileETag' set to None."
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	read -p  "Disable Etag header ? (a remote attacker could obtain informations on your system) (y/n):" ans
fi



echo "\n\n Exploration"
echo "##################################################"

# disable directory listing
read -p  "Disable directory listing ? (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	sed -i 's/ Indexes//g' $config && echo "Disabling directory listing: Removed parameter 'Indexes' from directive 'Options' for all directories."
	echo "# removed parameter 'Indexes' from directive 'Options' for all directories" >> $config
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	read -p  "Disable directory listing ? (y/n):" ans
fi



echo "\n\n Authentication bypass"
echo "##################################################"

# restrict method to get post head
read -p  "Restrict HTTP methods to GET, POST and HEAD ? (protect you from verb tampering attack if you plan to set basic authentication on your server later) (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	sed -i 's@<Directory /var/www/>@<Directory /var/www/>\n\t<LimitExcept GET POST HEAD>\n\t\tdeny from all\n\t</LimitExcept>@g' $config && echo "HTTP method restricted to GET, POST and HEAD."
	echo "# http method restricted to GET, POST and HEAD for directory /var/www" >> $config
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	read -p  "Restrict HTTP methods to GET, POST and HEAD ? (protect you from verb tampering attack if you plan to set basic authentication on your server later) (y/n):" ans
fi



echo "\n\n XSS, XST, Clickjacking"
echo "##################################################"

# set cookie with HttpOnly and Secure flag
read -p  "Set cookie with HttpOnly and Secure flag ? (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	a2enmod headers
	echo 'Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure' >> $config && echo "Added 'HttpOnly' and 'Secure' flag to cookies emitted by the server."
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	read -p  "Set cookie with HttpOnly and Secure flag ? (y/n):" ans
fi


# add header X-XSS-Protection
read -p  "Add header X-XSS-Protection ? (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	a2enmod headers
	echo 'Header set X-XSS-Protection "1; mode=block"' >> $config && echo "Added X-XSS-Protection header."
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	read -p  "Add header X-XSS-Protection ? (y/n):" ans
fi


# disable trace method
read -p  "Disable TRACE method ? (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	echo 'TraceEnable off' >> $config && echo "Disabling TRACE method: Directive 'TraceEnable' set to off."
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	read -p  "Disable TRACE method ? (y/n):" ans
fi


# enable X-Frame-Options header
read -p  "Enable X-Frame-Options header ? (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	a2enmod headers
	echo 'Header always append X-Frame-Options SAMEORIGIN' >> $config && echo "Enabling X-Frame-Options header: header value set to 'SAMEORIGIN'."
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	read -p  "Enable X-Frame-Options header ? (y/n):" ans
fi



echo "\n\n DDoS (Slowloris)"
echo "##################################################"

# decrease timeout value from 300 to 40
read -p  "Decrease the value of 'Timeout' directive from 300 to 40 ? (y/n):" ans
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
	echo 'ServerSignature Off' >> $config && echo "Disabling server signature on error pages: Directive 'ServerSignature' set to off."
elif [ "$ans" = "n" ] || [ "$ans" = "N" ]; then
	echo "Endach says NO!"
else
	sed -i 's@^\(Timeout\) 300@\1 40@g' $config && echo "Changed 'Timeout' value to 40."
	echo "# changed 'Timeout' value to 40 (default was 300)" >> $config
fi






echo  "\n[info] Restarting Apache server ...\n"
service apache2 restart
service apache2 status

clear
echo  "Little hedgehog fluffed his spikes, your Apache configuration now has a first minimal layer of security !\n"

echo '          ./////////.   '
echo '         /////////////  '
echo '        /. `/////////// '
echo '       o__,_//////////° '

echo  "\nIf you feel like I messed up your configuration, don't panic and run :\nsudo cp $backup $config"
echo  "\nRegards (^~^)"
